/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package practice.app

import practice.list.LinkedList

import static practice.utilities.StringUtils.join
import static practice.utilities.StringUtils.split
import static practice.app.MessageUtils.getMessage

import org.apache.commons.text.WordUtils

class App {
    static void main(String[] args) {
        LinkedList tokens
        tokens = split(getMessage())
        String result = join(tokens)
        println(WordUtils.capitalize(result))
    }
}
